[workspace]
authors = ["Brian E. Granger <ellisonbg@gmail.com>"]
channels = ["conda-forge"]
name = "jupyter-ai-claude-code"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
start = "jupyter lab"

[dependencies]
jupyterlab = ">=4.4.0,<4.5"
python = ">=3.8"
hatchling = "*"

[pypi-dependencies]
jupyter-ai = ">=3.0.0b5"
jupyter-ai-magics = ">=3.0.0b5"
claude-code-sdk = "*"
jupyter_server_documents = "*"
jupyter-ai-claude-code = { path = ".", editable = true }

